import type { Item } from "./content";

/**
 * News desk. Each story is our own rewrite of facts reported elsewhere, written in
 * DesignersDream's voice under Barry's byline. Every story credits and links its sources.
 * Never paste text from the original report: summarise the facts and add our take.
 */
export const NEWS: Item[] = [
  {
    type: "news",
    slug: "adobe-premiere-free-on-android",
    title: "Adobe Premiere is now free on Android, with 4K exports and no watermark",
    excerpt: "The mobile version of Premiere has landed on Android. You don't need a Creative Cloud plan or even an Adobe account to start editing.",
    disciplines: ["motion"],
    date: "2026-10-05",
    featured: true,
    readMins: 3,
    author: "barry",
    sources: [{ name: "Creative Bloq", url: "https://www.creativebloq.com/photography/video-editing-software/free-premiere-on-android-is-exactly-the-direction-adobe-should-be-taking" }],
    body: [
      "Premiere's phone app started on iPhone. Now it's on Android too, and the headline is the price: free, with no Creative Cloud subscription and no Adobe account needed to get going.",
      "## What you get for nothing",
      "- A multi-track timeline with frame-accurate trimming.",
      "- Voice-over recording straight into the edit.",
      "- Enhance Audio, which cleans up background noise.",
      "- Creator templates for quick social cuts.",
      "- Unlimited 4K exports, with no watermark, ads or upgrade nags.",
      "## What costs extra",
      "The Firefly tools, such as Generative Fill, Image-to-Video and generated sound effects, use generative credits. Everything else in the core editor is free.",
      "## What's missing for now",
      "Keyframes, beat detection, Adobe Fonts, better captions and opening projects on desktop are all marked as coming soon. You also need Android 13 or later and at least 5 GB of RAM, so cheaper phones are left out.",
      "## Our take",
      "This is Adobe going after CapCut's audience directly. For designers who cut reels, client previews or behind-the-scenes clips on the move, a free editor with clean 4K exports is a real option. Once keyframes arrive, it becomes a serious one.",
    ],
  },
  {
    type: "news",
    slug: "mountain-logos-2026-trend",
    title: "Why so many 2026 logos are drawing mountains",
    excerpt: "From the Alpes 2030 Winter Olympics to Vermont tourism, peaks are everywhere this year. The good ones draw a real mountain, not a generic triangle.",
    disciplines: ["brand", "graphic"],
    date: "2026-10-04",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Creative Bloq", url: "https://www.creativebloq.com/design/logos-icons/everyones-making-mountain-inspired-logos-in-2026-heres-what-that-tells-us" }],
    body: [
      "Mountains have always been a branding shortcut for strength and adventure. Think of The North Face's nod to Half Dome or Patagonia's Fitz Roy skyline. In 2026 the shortcut is back in a big way.",
      "## This year's peaks",
      "- **Alpes 2030 Winter Olympics**: converging lines that form a summit, coloured in the pinks and reds of alpine glow at sunrise and sunset.",
      "- **Vermont tourism**: a hand-lettered wordmark where the m traces Camel's Hump and a moon sits in the o.",
      "- **Utah Mammoth**: the NHL team's crest folds the Wasatch range and the shape of the state into a crown.",
      "## The lesson: be specific",
      "The marks that work point at a real, nameable mountain. Toblerone shows the other side: when production moved partly out of Switzerland, it had to drop the Matterhorn for a generic peak, and the logo lost some of its story.",
      "There's a wider point too. As AI fills feeds with interchangeable imagery, a reference people can actually visit, photograph and recognise carries more weight than a pretty triangle.",
      "## Try it",
      "If your brief calls for a landscape motif, start from a real place the client cares about. Sketch its actual silhouette before you simplify it.",
    ],
  },
  {
    type: "news",
    slug: "ltx-2-5-vfx-tools",
    title: "LTX-2.5 adds VFX tools: alpha mattes, HDR and blockout-to-render",
    excerpt: "Lightricks' open video model now pulls clean mattes around hair, smoke and glass, and can turn rough 3D layouts into finished-looking shots.",
    disciplines: ["motion", "3d"],
    date: "2026-10-04",
    readMins: 3,
    author: "barry",
    sources: [
      { name: "CG Channel", url: "https://www.cgchannel.com/2026/10/new-3d-software-you-may-have-missed-4-october-2026/" },
      { name: "LTX", url: "https://ltx.io/solution/vfx" },
    ],
    body: [
      "Lightricks used its VFX Week to add a set of production tools to LTX-2.5, its open-weights video model. The pitch is less about generating clips from scratch and more about fixing and finishing real footage.",
      "## The new tools",
      "- **Alpha Gen** pulls soft-edged mattes, including the hard cases like hair, fur, smoke, fire, sheer fabric, glass and water.",
      "- **Layout to Render** turns a rough 3D blockout into a rendered-looking shot that keeps your camera and composition.",
      "- **SDR to HDR** and native 16-bit EXR output for grading.",
      "- **Refine**, **Restore** and **Native Resolution** for upscaling, cleaning archive footage and working at full delivery size.",
      "## How to use it",
      "The weights are free on Hugging Face and work with ComfyUI. Lightricks says it runs locally on a 12 GB graphics card. If you'd rather not run it yourself, the LTX Studio web app uses credit-based pricing.",
      "## Why it matters",
      "Rotoscoping is the job nobody wants. A model that can pull a usable matte around flyaway hair saves hours, and running it locally keeps client footage off someone else's servers. As always, check the output frame by frame before it goes into a final comp.",
    ],
  },
  {
    type: "news",
    slug: "pftrack-solo-unlocked",
    title: "PFTrack Solo unlocks 37 pro nodes for freelancers",
    excerpt: "The solo edition of the camera tracker now includes photogrammetry, stereo solving and optical flow. The perpetual price goes up to £999.",
    disciplines: ["3d", "motion"],
    date: "2026-10-04",
    readMins: 2,
    author: "barry",
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/10/the-pixel-farm-lifts-feature-restrictions-on-pftrack-solo/" }],
    body: [
      "The Pixel Farm has removed most of the limits on PFTrack Solo, the version of its camera-tracking app for one-person studios. From PFTrack 26.09.30, Solo users get 37 nodes that used to be Studio and Enterprise only.",
      "## Newly included",
      "- The photogrammetry pipeline.",
      "- Tracking for stereo, spherical and equirectangular footage.",
      "- Z-depth generation, Optical Flow and the Mocap Solver.",
      "- Video retiming utilities.",
      "## The catch",
      "A perpetual licence now costs £999, up from £699. There are new rent-to-own plans: £184.99 a month for six months or £39.99 a week for 30 weeks. The seven-day trial has been replaced by a demo mode that can't save or export.",
      "Solo is still one user on one machine. The Python API, command-line processing and RED or ARRI RAW debayering remain in the bigger editions. It runs on Windows, macOS and Rocky Linux.",
      "## Who it's for",
      "Freelancers doing match-moves for ads and music videos who kept hitting the old feature wall. If you only track the odd shot, Blender's built-in tracker is still free.",
    ],
  },
  {
    type: "news",
    slug: "adobe-patent-text-to-3d-worlds",
    title: "An Adobe patent shows typing a sentence to build a 3D world",
    excerpt: "The filing describes turning a prompt like ‘a foggy Japanese garden at dusk’ into a space you can walk around in.",
    disciplines: ["3d"],
    date: "2026-10-04",
    readMins: 2,
    author: "barry",
    sources: [{ name: "Creative Bloq", url: "https://www.creativebloq.com/design/graphic-design/adobes-ai-text-to-3d-world-concept-is-a-glimpse-of-where-firefly-could-go-next" }],
    body: [
      "A newly published US patent filing from Adobe describes a system that builds navigable 3D environments from a text description.",
      "## How it would work",
      "It runs in two stages. First an AI model creates a spherical, 360-degree image of the scene from your prompt. A second model then turns that image into real 3D geometry that you can view from different angles and move through.",
      "## Read it as a direction, not a product",
      "A patent isn't a launch date, and companies file plenty of ideas they never ship. Still, it fits a pattern: Adobe has published dozens of related filings, covering AI-generated camera angles, matching materials across 3D models and virtual try-on for clothing.",
      "Adobe's Substance apps, including Substance 3D Painter and Modeler, don't have Firefly tools yet. If this ever ships, that's the obvious home for it.",
    ],
  },
  {
    type: "news",
    slug: "caddis-1-1-motion-graphics",
    title: "Caddis 1.1 gives this new motion graphics app particles and loops",
    excerpt: "The node-and-layer motion tool adds a particle system with flocking, loop and switch controls, grid layouts and Cryptomatte support.",
    disciplines: ["motion"],
    date: "2026-10-03",
    readMins: 2,
    author: "barry",
    sources: [
      { name: "CG Channel", url: "https://www.cgchannel.com/2026/10/new-3d-software-you-may-have-missed-4-october-2026/" },
      { name: "Caddis", url: "https://www.caddis.app/" },
    ],
    body: [
      "Caddis is a young motion graphics app from developer Mike Gaynor. It lets you work with nodes or with layers, whichever suits the shot. Version 1.1 makes it feel much more grown up.",
      "## New in 1.1",
      "- A particle system with collisions and flocking.",
      "- Loop, For Each and Switch controls for building procedural setups.",
      "- Grid layouts using new Layout and Cell nodes.",
      "- Cryptomatte EXR support and nested compositions.",
      "## Our take",
      "Motion design tools are getting interesting again. Between Caddis, Cavalry and Figma's new motion features, After Effects has real competition for procedural, system-driven work. Caddis is worth a weekend if you like building with rules rather than keyframes.",
    ],
  },
  {
    type: "news",
    slug: "nothing-paper-cup-fold-down-lid",
    title: "A paper cup that folds into its own lid",
    excerpt: "Florida start-up Nothing has designed takeaway cups whose sides fold down into a lid, removing the plastic lid altogether.",
    disciplines: ["brand", "graphic"],
    date: "2026-10-02",
    readMins: 2,
    author: "barry",
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/10/02/nothing-takeaway-paper-cup/" }],
    body: [
      "Nothing (the Florida company, not the phone maker) began by making paper straws. Brothers Brandon and Jordan Leeds noticed those straws were going into plastic cups with plastic lids, so they redesigned the cup.",
      "## How it works",
      "The walls of the cup are taller than usual and fold down to close it. The hot cup uses three flaps that lock into a drinking spout. The cold cup has four folds with room for a straw.",
      "## Materials",
      "A water-based coating bonds to the paper fibres instead of a plastic lining. It's certified plastic-free and home-compostable, breaking down within 180 days in a back-garden heap, and it can also be recycled.",
      "## For packaging designers",
      "It's a neat reminder that the most sustainable part is often the part you remove. The folded lid also changes the printable area, which gives brands new space for graphics on top of the cup.",
    ],
  },
  {
    type: "news",
    slug: "freckle-phone-for-kids",
    title: "Freckle is a phone designed to send kids outside",
    excerpt: "No browser, no app store and no social media. Instead: quests, a camera that identifies bugs and plants, and maps for walking the neighbourhood.",
    disciplines: ["ui-ux"],
    date: "2026-10-01",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/10/01/freckle-phone-sends-kids-outside/" }],
    body: [
      "Freckle is a phone for children aged 7 to 13, built with design studio Body Shop and founded by Sam Terris. Its goal is the opposite of most screens: get kids exploring, then get out of the way.",
      "## The product design",
      "It comes in a rugged case with a lanyard, so it hangs around the neck like binoculars, and kids can decorate it with charms. The custom ClayOS software has a soft, clay-like look with friendly characters.",
      "## The interface choices",
      "- **Quests**: ready-made or parent-written missions, like finding five different insects.",
      "- **Discovery camera**: identifies plants, animals and objects.",
      "- Kid-friendly maps, a walkie-talkie mode, a music player and preloaded credit for buses and small purchases.",
      "- No browser, no app store and no social media.",
      "## AI with tight limits",
      "There are three narrow AI tools, each with its own character: one answers questions, one recognises things, one tells stories. There's no open-ended chatbot. Parents get alerts when a child leaves a safe zone or meets a sensitive topic like bullying, not a full activity log, and the company says children's data won't be used for AI training.",
      "Freckle is due to ship in the US in December. For UX designers it's a useful case study in designing by subtraction.",
    ],
  },
  {
    type: "news",
    slug: "the-last-museum-art-search-engine",
    image: { src: "/art/the-last-museum-art-search-engine.webp", alt: "Illustration of framed artworks floating in a glowing grid around a search bar" },
    title: "The Last Museum lets you search six million artworks by mood",
    excerpt: "A free search engine that understands plain descriptions like ‘japanese woodblock print of birds’ just became the best reference board on the internet.",
    disciplines: ["graphic", "brand", "3d"],
    date: "2026-10-02",
    readMins: 3,
    author: "barry",
    sources: [
      { name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" },
      { name: "The Last Museum", url: "https://lastmuseum.com/" },
    ],
    body: [
      "Every designer has lost an afternoon digging through museum websites for one specific reference. The Last Museum wants to end that. It's a search engine that pulls collections from major museums into one place, and it now indexes more than six million works.",
      "## You search the way you think",
      "The trick is semantic search. Instead of needing an artist's name or a catalogue number, you type what you're picturing: propaganda poster, renaissance portrait, abstract geometric shapes. Results come back ranked by meaning, and you can narrow them by date, all the way back to 3000 BC.",
      "## Free, with public-domain downloads",
      "It's free to use, and where a work is in the public domain the site links straight to a download. That makes it useful for more than moodboards: think editorial illustration, packaging with a heritage feel, or a pitch deck that needs real historical texture instead of stock photography.",
      "## Why it matters",
      "- Reference gathering gets faster, especially for brand and editorial work with a historical angle.",
      "- Public-domain pieces can be used directly, but check each work's licence before it goes into anything commercial.",
      "- The makers say the goal is to index every museum's art eventually, so the archive should keep growing.",
      "Bookmark it next to your usual reference sites. The first time you find exactly the right 1920s poster in ten seconds, you'll wonder how you managed without it.",
    ],
  },
  {
    type: "news",
    slug: "three-small-tools-pigment-smol-avellio",
    image: { src: "/art/three-small-tools-pigment-smol-avellio.webp", alt: "Illustration of a colour swatch fan, a vice squeezing files and a magnifying glass over type" },
    title: "Three small tools worth a look this month",
    excerpt: "A free palette generator, a local file squeezer for Mac and a typography checker for InDesign. None of them need a subscription to be useful.",
    disciplines: ["graphic", "web", "brand"],
    date: "2026-10-02",
    readMins: 3,
    author: "barry",
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Not every useful tool arrives with a keynote. These three turned up in CreativePro's October roundup, and each solves one annoying job well.",
      "## Pigment, for palettes that actually sit together",
      "ShapeFactory's Pigment builds colour schemes from lighting and pigment settings rather than random hue jumps, so the results feel like they belong in the same room. It's free and exports to Adobe Swatch Exchange, SVG or Sketch.",
      "## Smol, for shrinking files without uploading them",
      "Smol is a Mac app that compresses and converts images, PDFs, video and audio entirely on your machine. It batch-processes, strips metadata and can upscale with AI. It costs $29 once, with no subscription and no quotas, which is refreshing.",
      "## Avellio, for typography QA in InDesign",
      "Avellio adds a proofing pass to InDesign that flags style overrides, spacing problems, widows and orphans before a document goes to print. Pricing is $40 a year for solo users or $70 for a lifetime licence.",
      "## Our take",
      "If you send client files by email, Smol pays for itself quickly. If you lay out long documents, Avellio catches the mistakes that are embarrassing to explain after the print run. Pigment is simply a nice way to start a palette.",
    ],
  },
  {
    type: "news",
    slug: "vauxhall-griffin-logo-drops-flag",
    image: { src: "/art/vauxhall-griffin-logo-drops-flag.webp", alt: "Illustration of a glowing griffin badge on the grille of an electric car at night" },
    title: "Vauxhall's griffin loses its flag for the first time in 121 years",
    excerpt: "The British carmaker has flattened and sharpened its emblem again, this time so it reads clearly when it lights up on electric cars.",
    disciplines: ["brand", "graphic"],
    date: "2026-10-01",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/09/30/vauxhall-griffin-logo-streamline/" }],
    body: [
      "Vauxhall has redrawn its griffin again, and the biggest change is what's missing. The flag bearing a letter V, which the creature has held since the early days of the emblem, is gone for the first time in 121 years.",
      "## What changed",
      "- The griffin is more angular than the flat version Vauxhall introduced in 2020.",
      "- Its neck hair is simplified and its beak is now closed.",
      "- The V flag has been removed entirely.",
      "## Why: logos that glow",
      "According to Vauxhall's design leadership, the goal was to keep the griffin recognisable while making it cleaner for electric vehicles, where the badge is often illuminated. Fine details that look rich in chrome turn into noise when they're backlit, so they had to go.",
      "The new emblem debuts on the STX Concept at the Paris Motor Show in October and will appear on production models from next year.",
      "## The bigger pattern",
      "Car brands keep simplifying their marks, and lighting is a big reason why. If you design marks for products, test them as a glowing shape on a dark background, at small sizes and at a distance. A logo that only works printed on paper now has a shorter life.",
      "The original griffin was drawn in 1915 by Harry Varley, an apprentice at the company. It's a nice reminder that good identity work can be refined for a century without losing what made it work in the first place.",
    ],
  },
  {
    type: "news",
    slug: "moma-full-disclosure-information-design",
    image: { src: "/art/moma-full-disclosure-information-design.webp", alt: "Illustration of a museum visitor looking at data postcards, a large map and dreamlike memory images" },
    title: "MoMA's new show asks what information design looks like in the AI era",
    excerpt: "Full Disclosure runs until June 2027 and puts handmade data postcards next to AI images generated from people's memories.",
    disciplines: ["graphic", "ui-ux"],
    date: "2026-09-30",
    readMins: 4,
    author: "barry",
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/09/30/moma-information-design-exhibition-full-disclosure/" }],
    body: [
      "The Museum of Modern Art in New York has opened Full Disclosure: The Edge of Information Design, a ground-floor exhibition curated by Paola Antonelli. It runs from 27 September 2026 to 13 June 2027.",
      "## From infographics to synthetic memories",
      "The show traces information design from familiar charts and maps to projects that stretch the definition. The most talked-about piece is the Synthetic Memories Archive by the Spanish studio Domestic Data Streamers. It uses AI to turn people's spoken memories into images, displayed beside the descriptions that produced them. The studio has also explored the approach as a support for people living with trauma or dementia.",
      "## Other works on show",
      "- Dear Data by Giorgia Lupi and Stefanie Posavec, the handmade postcards that turned everyday habits into drawings.",
      "- Calculating Empires by Kate Crawford and Vladan Joler, a three-wall map of technology and power since 1500.",
      "- The Seizure of the Iuventa by Forensic Architecture, an investigation into the case against a sea rescue NGO.",
      "- Two Sides of the Same Coin by Laura Kurgan and Dan Miller, linking land use with microbial life.",
      "- A work by William Villalongo and Shraddha Raman extending W.E.B. Du Bois's pioneering data portraits of Black Americans.",
      "## Why designers should care",
      "The exhibition makes an argument every interface and dashboard designer will recognise: presenting information is never neutral. Choices about what to show, what to leave out and how to make it feel are design decisions with consequences. If you're in New York before next summer, it's worth an hour. If not, the projects are well documented online and make a strong reading list.",
    ],
  },
  {
    type: "news",
    slug: "adobe-max-2026-miami-beach-dates",
    image: { src: "/art/adobe-max-2026-miami-beach-dates.webp", alt: "Illustration of a night-time conference stage among palm trees and art deco buildings" },
    title: "Adobe MAX 2026 is set for Miami Beach, 10 to 12 November",
    excerpt: "Adobe's big creative conference returns in November, in person and online. Here's what we know so far and how to follow along.",
    disciplines: ["graphic", "motion", "brand", "ui-ux"],
    date: "2026-09-29",
    readMins: 2,
    author: "barry",
    sources: [{ name: "Adobe MAX", url: "https://max.adobe.com/" }],
    body: [
      "Adobe MAX, the conference where Adobe usually saves its biggest Creative Cloud and Firefly announcements, takes place from 10 to 12 November 2026 in Miami Beach, Florida. Pre-conference training runs on 8 and 9 November, and you can also attend online.",
      "## Sneaks gets a new host",
      "Actor Terry Crews will host MAX Sneaks, the session where Adobe engineers show early experiments that may or may not become real features. It's often the most fun part of the event, and a decent preview of where the tools are heading.",
      "## What to expect",
      "Adobe hasn't published its announcement list, and we won't guess at it. This year the company has been expanding its AI creative agent across Firefly and Creative Cloud apps, so expect that to feature heavily.",
      "## Should you go?",
      "- Students, educators, non-profit and government staff get lower rates, and early registration is cheaper.",
      "- If budget is tight, the online sessions and the keynote recordings cover most of what matters.",
      "We'll publish a plain-English roundup of everything that matters to working designers the week of the event.",
    ],
  },
  {
    type: "news",
    slug: "canva-september-update-brand-kit-from-url",
    title: "Canva can now build a brand kit from a website address",
    excerpt: "September's Canva update also turns hand-drawn shapes into image frames and adds analytics and payment links to Canva websites.",
    disciplines: ["brand", "web", "graphic"],
    date: "2026-09-27",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Canva Design School", url: "https://www.canva.com/design-school/resources/whats-new-canva-sep26/" }],
    body: [
      "Canva's September release is a grab-bag, but a few of the changes will save real time for designers working with small clients.",
      "## Brand kits from a URL",
      "Paste a website address and Canva will generate a brand kit from it. For freelancers onboarding a client who has a site but no brand guidelines, that's a useful head start. Treat the result as a draft: automated extraction can pick up stray colours or the wrong fonts, so check it before you share it with the client.",
      "## Frames from your own doodles",
      "You can now draw a shape by hand and turn it into an image frame. It's a small thing, but it opens up more expressive photo layouts without opening another app.",
      "## Websites, sheets and whiteboards",
      "- Canva websites get custom navigation, buttons and Google Analytics tracking.",
      "- A PayPal app lets you embed payment links directly in designs.",
      "- Sheets adds tags, filters and conditional formatting.",
      "- Whiteboards gain sections and direct linking.",
      "- A Code feature can generate visual dashboards from spreadsheets and web research.",
      "## Our take",
      "Canva keeps moving from making graphics to running whole small-business workflows. If your clients already live in Canva, these updates make it easier to hand over files they can keep up to date themselves.",
    ],
  },
  {
    type: "news",
    slug: "midjourney-v8-2-edit-model",
    title: "Midjourney's V8.2 edit model lets you change images with plain instructions",
    excerpt: "Inpainting, outpainting and up to four reference images arrived over the last month, along with live style previews.",
    disciplines: ["graphic", "brand", "3d"],
    date: "2026-09-25",
    readMins: 3,
    author: "barry",
    sources: [
      { name: "Midjourney updates", url: "https://updates.midjourney.com/" },
      { name: "Releasebot", url: "https://releasebot.io/updates/midjourney" },
    ],
    body: [
      "Midjourney spent September making its V8 generation of models much easier to steer after the first image comes out.",
      "## Edit with a sentence",
      "The V8.2 edit model, which first appeared on 27 August, lets you change an image by describing the change. It handles inpainting and outpainting, and you can attach up to four reference images to guide the edit. Since 2 September it has been available directly in the lightbox, so you no longer need a separate editing step.",
      "## Style previews and seamless tiles",
      "- The Styles sidebar can now show what your latest prompt would look like across different styles before you commit.",
      "- You can save default parameters so every new prompt starts the way you like.",
      "- Tile generation for V8.1 and V8.2 now blends seams better, which matters for patterns and textures.",
      "## What it means for your workflow",
      "Instruction-based editing is where AI image tools become practical for client work. Instead of re-rolling until a hand looks right, you fix the hand. Reference images help keep a product or character consistent across a set. You'll still need to finish the work in your own tools, but the gap between a first draft and something usable is getting smaller.",
      "As always with generated imagery, check the terms of your plan and your client's policy on AI-made assets before anything ships.",
    ],
  },
  {
    type: "news",
    slug: "mclaren-new-logo-garage-sign",
    title: "McLaren's new logo comes from a garage sign in Auckland",
    excerpt: "An all-caps wordmark, a custom typeface and a palette pulled from an old photo of Bruce McLaren. Heritage done with restraint.",
    disciplines: ["brand", "graphic"],
    date: "2026-09-23",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Carscoops", url: "https://www.carscoops.com/2026/09/mclaren-new-logo/" }],
    body: [
      "McLaren Automotive revealed a new identity on 22 September, and the story behind it is a good one. The wordmark takes its cue from the sign of a service station in Auckland, New Zealand, owned by Bruce McLaren's parents. It was in that garage that the young McLaren modified the 1929 Austin Seven that gave him his first racing win.",
      "## What's new",
      "- A custom typeface, McLaren Sans.",
      "- An all-uppercase wordmark, replacing the previous mixed-case logo.",
      "- A distinctive horizontal line beneath the C.",
      "- A refined palette taken from a photograph of Bruce McLaren: Papaya orange, Ember, Midnight blue, Black, Anthracite, Colnbrook silver and Mist white.",
      "The work was led by David Woodhouse, McLaren Automotive's chief creative officer. The identity will appear on cars, starting with the McL 6GT, and across merchandise and digital channels as it rolls out.",
      "## Why it works",
      "Heritage rebrands often go wrong by copying the past too literally. This one borrows a single, specific detail from the brand's origin story and builds a modern system around it. The colour names do quiet storytelling too. It's a useful example to keep for your next pitch to a client with a long history.",
    ],
  },
  {
    type: "news",
    slug: "affinity-3-3-canva-prosuite",
    title: "Affinity 3.3 lands with a Blend tool, InDesign import and a new ProSuite",
    excerpt: "Canva's free all-in-one design app gets more than 60 features, and now sits in a professional bundle with Cavalry, Flourish and Leonardo.",
    disciplines: ["graphic", "brand", "motion"],
    date: "2026-09-16",
    featured: true,
    readMins: 4,
    author: "barry",
    sources: [
      { name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" },
      { name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" },
    ],
    body: [
      "Canva released Affinity 3.3 on 15 September. Affinity is the app that combines photo editing, vector design and page layout in one place, and it's still free to use with a Canva account on Windows and macOS.",
      "## The headline features",
      "- A Blend tool that morphs one shape into another along a curve, something illustrators have wanted for years.",
      "- A Mask tool, a Deform tool and new saturation and hue curves for image editing.",
      "- Import of InDesign INDD files, which makes switching away from Adobe for layout work far more realistic.",
      "- A JavaScript-based Scripting Studio for automating repetitive jobs.",
      "- Photography upgrades including RAW presets, better sharpening and a dedicated astrophotography workspace.",
      "## Meet ProSuite",
      "Canva also introduced ProSuite, its name for a family of professional tools: Affinity for design, Cavalry for motion graphics, Flourish for data visualisation and Leonardo for generative AI. For now they remain separate apps, with closer integration planned. Affinity and Cavalry stay free; the AI features need a paid Canva plan.",
      "## Should you switch?",
      "If you've been waiting for INDD import before trying Affinity for layout, now is the time to test it on a real project. Open an old InDesign file, check fonts and styles carefully, and see how much survives. For many freelancers, a capable free tool is now a genuine alternative to a subscription.",
    ],
  },
  {
    type: "news",
    slug: "figma-nested-folders-ai-credit-limits",
    image: { src: "/art/figma-nested-folders-ai-credit-limits.webp", alt: "Illustration of colourful folders nested inside each other, many layers deep" },
    title: "Figma projects become nested folders, ten levels deep",
    excerpt: "Teams can finally organise files the way they think, and admins get per-person limits on AI credits.",
    disciplines: ["ui-ux", "web"],
    date: "2026-08-05",
    readMins: 2,
    author: "barry",
    sources: [{ name: "Figma release notes", url: "https://www.figma.com/release-notes/" }],
    body: [
      "Two quality-of-life changes landed in Figma in early August, and both matter more for big teams than the flashier launches do.",
      "## Projects are now folders",
      "Every team file now lives in a folder, and folders can nest up to ten levels deep. You can colour-code them, and nested folders inherit access permissions from their parent, with the option to restrict a folder to specific people. If your team has been faking hierarchy with naming conventions like ‘2026 / Client / Web / v3’, you can finally stop.",
      "## Limits on AI credits",
      "Admins can now set a custom AI credit limit for individual people. When someone hits their limit, they can request more from an admin rather than being stuck. It's a sensible control as AI features use up more of each plan's credits.",
      "## Quick tip",
      "Before restructuring, agree a folder template with your team, for example Client → Project → Phase, so everyone files work the same way from day one.",
    ],
  },
];
