import type { Item } from "./content";

/**
 * News desk. Each story is our own rewrite of facts reported elsewhere, written in
 * DesignersDream's voice under Barry's byline. Every story credits and links its sources.
 * Never paste text from the original report: summarise the facts and add our take.
 */
export const NEWS: Item[] = [
  {
    type: "news",
    slug: "the-last-museum-art-search-engine",
    image: { src: "/art/the-last-museum-art-search-engine.webp", alt: "Illustration of framed artworks floating in a glowing grid around a search bar" },
    title: "The Last Museum lets you search six million artworks by mood",
    excerpt: "A free search engine that understands plain descriptions like ‘japanese woodblock print of birds’ just became the best reference board on the internet.",
    disciplines: ["graphic", "brand", "3d"],
    date: "2026-10-02",
    featured: true,
    readMins: 3,
    author: "barry",
    sources: [
      { name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" },
      { name: "The Last Museum", url: "https://lastmuseum.com/" },
    ],
    body: [
      "Every designer has lost an afternoon digging through museum websites for one specific reference. The Last Museum wants to end that. It's a search engine that pulls collections from major museums into one place, and it now indexes more than six million works.",
      "## You search the way you think",
      "The trick is semantic search. Instead of needing an artist's name or a catalogue number, you type what you're picturing: propaganda poster, renaissance portrait, abstract geometric shapes. Results come back ranked by meaning, and you can narrow them by date, all the way back to 3000 BC.",
      "## Free, with public-domain downloads",
      "It's free to use, and where a work is in the public domain the site links straight to a download. That makes it useful for more than moodboards: think editorial illustration, packaging with a heritage feel, or a pitch deck that needs real historical texture instead of stock photography.",
      "## Why it matters",
      "- Reference gathering gets faster, especially for brand and editorial work with a historical angle.",
      "- Public-domain pieces can be used directly, but check each work's licence before it goes into anything commercial.",
      "- The makers say the goal is to index every museum's art eventually, so the archive should keep growing.",
      "Bookmark it next to your usual reference sites. The first time you find exactly the right 1920s poster in ten seconds, you'll wonder how you managed without it.",
    ],
  },
  {
    type: "news",
    slug: "three-small-tools-pigment-smol-avellio",
    image: { src: "/art/three-small-tools-pigment-smol-avellio.webp", alt: "Illustration of a colour swatch fan, a vice squeezing files and a magnifying glass over type" },
    title: "Three small tools worth a look this month",
    excerpt: "A free palette generator, a local file squeezer for Mac and a typography checker for InDesign. None of them need a subscription to be useful.",
    disciplines: ["graphic", "web", "brand"],
    date: "2026-10-02",
    readMins: 3,
    author: "barry",
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Not every useful tool arrives with a keynote. These three turned up in CreativePro's October roundup, and each solves one annoying job well.",
      "## Pigment, for palettes that actually sit together",
      "ShapeFactory's Pigment builds colour schemes from lighting and pigment settings rather than random hue jumps, so the results feel like they belong in the same room. It's free and exports to Adobe Swatch Exchange, SVG or Sketch.",
      "## Smol, for shrinking files without uploading them",
      "Smol is a Mac app that compresses and converts images, PDFs, video and audio entirely on your machine. It batch-processes, strips metadata and can upscale with AI. It costs $29 once, with no subscription and no quotas, which is refreshing.",
      "## Avellio, for typography QA in InDesign",
      "Avellio adds a proofing pass to InDesign that flags style overrides, spacing problems, widows and orphans before a document goes to print. Pricing is $40 a year for solo users or $70 for a lifetime licence.",
      "## Our take",
      "If you send client files by email, Smol pays for itself quickly. If you lay out long documents, Avellio catches the mistakes that are embarrassing to explain after the print run. Pigment is simply a nice way to start a palette.",
    ],
  },
  {
    type: "news",
    slug: "vauxhall-griffin-logo-drops-flag",
    image: { src: "/art/vauxhall-griffin-logo-drops-flag.webp", alt: "Illustration of a glowing griffin badge on the grille of an electric car at night" },
    title: "Vauxhall's griffin loses its flag for the first time in 121 years",
    excerpt: "The British carmaker has flattened and sharpened its emblem again, this time so it reads clearly when it lights up on electric cars.",
    disciplines: ["brand", "graphic"],
    date: "2026-10-01",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/09/30/vauxhall-griffin-logo-streamline/" }],
    body: [
      "Vauxhall has redrawn its griffin again, and the biggest change is what's missing. The flag bearing a letter V, which the creature has held since the early days of the emblem, is gone for the first time in 121 years.",
      "## What changed",
      "- The griffin is more angular than the flat version Vauxhall introduced in 2020.",
      "- Its neck hair is simplified and its beak is now closed.",
      "- The V flag has been removed entirely.",
      "## Why: logos that glow",
      "According to Vauxhall's design leadership, the goal was to keep the griffin recognisable while making it cleaner for electric vehicles, where the badge is often illuminated. Fine details that look rich in chrome turn into noise when they're backlit, so they had to go.",
      "The new emblem debuts on the STX Concept at the Paris Motor Show in October and will appear on production models from next year.",
      "## The bigger pattern",
      "Car brands keep simplifying their marks, and lighting is a big reason why. If you design marks for products, test them as a glowing shape on a dark background, at small sizes and at a distance. A logo that only works printed on paper now has a shorter life.",
      "The original griffin was drawn in 1915 by Harry Varley, an apprentice at the company. It's a nice reminder that good identity work can be refined for a century without losing what made it work in the first place.",
    ],
  },
  {
    type: "news",
    slug: "moma-full-disclosure-information-design",
    image: { src: "/art/moma-full-disclosure-information-design.webp", alt: "Illustration of a museum visitor looking at data postcards, a large map and dreamlike memory images" },
    title: "MoMA's new show asks what information design looks like in the AI era",
    excerpt: "Full Disclosure runs until June 2027 and puts handmade data postcards next to AI images generated from people's memories.",
    disciplines: ["graphic", "ui-ux"],
    date: "2026-09-30",
    readMins: 4,
    author: "barry",
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/09/30/moma-information-design-exhibition-full-disclosure/" }],
    body: [
      "The Museum of Modern Art in New York has opened Full Disclosure: The Edge of Information Design, a ground-floor exhibition curated by Paola Antonelli. It runs from 27 September 2026 to 13 June 2027.",
      "## From infographics to synthetic memories",
      "The show traces information design from familiar charts and maps to projects that stretch the definition. The most talked-about piece is the Synthetic Memories Archive by the Spanish studio Domestic Data Streamers. It uses AI to turn people's spoken memories into images, displayed beside the descriptions that produced them. The studio has also explored the approach as a support for people living with trauma or dementia.",
      "## Other works on show",
      "- Dear Data by Giorgia Lupi and Stefanie Posavec, the handmade postcards that turned everyday habits into drawings.",
      "- Calculating Empires by Kate Crawford and Vladan Joler, a three-wall map of technology and power since 1500.",
      "- The Seizure of the Iuventa by Forensic Architecture, an investigation into the case against a sea rescue NGO.",
      "- Two Sides of the Same Coin by Laura Kurgan and Dan Miller, linking land use with microbial life.",
      "- A work by William Villalongo and Shraddha Raman extending W.E.B. Du Bois's pioneering data portraits of Black Americans.",
      "## Why designers should care",
      "The exhibition makes an argument every interface and dashboard designer will recognise: presenting information is never neutral. Choices about what to show, what to leave out and how to make it feel are design decisions with consequences. If you're in New York before next summer, it's worth an hour. If not, the projects are well documented online and make a strong reading list.",
    ],
  },
  {
    type: "news",
    slug: "adobe-max-2026-miami-beach-dates",
    image: { src: "/art/adobe-max-2026-miami-beach-dates.webp", alt: "Illustration of a night-time conference stage among palm trees and art deco buildings" },
    title: "Adobe MAX 2026 is set for Miami Beach, 10 to 12 November",
    excerpt: "Adobe's big creative conference returns in November, in person and online. Here's what we know so far and how to follow along.",
    disciplines: ["graphic", "motion", "brand", "ui-ux"],
    date: "2026-09-29",
    readMins: 2,
    author: "barry",
    sources: [{ name: "Adobe MAX", url: "https://max.adobe.com/" }],
    body: [
      "Adobe MAX, the conference where Adobe usually saves its biggest Creative Cloud and Firefly announcements, takes place from 10 to 12 November 2026 in Miami Beach, Florida. Pre-conference training runs on 8 and 9 November, and you can also attend online.",
      "## Sneaks gets a new host",
      "Actor Terry Crews will host MAX Sneaks, the session where Adobe engineers show early experiments that may or may not become real features. It's often the most fun part of the event, and a decent preview of where the tools are heading.",
      "## What to expect",
      "Adobe hasn't published its announcement list, and we won't guess at it. This year the company has been expanding its AI creative agent across Firefly and Creative Cloud apps, so expect that to feature heavily.",
      "## Should you go?",
      "- Students, educators, non-profit and government staff get lower rates, and early registration is cheaper.",
      "- If budget is tight, the online sessions and the keynote recordings cover most of what matters.",
      "We'll publish a plain-English roundup of everything that matters to working designers the week of the event.",
    ],
  },
  {
    type: "news",
    slug: "canva-september-update-brand-kit-from-url",
    title: "Canva can now build a brand kit from a website address",
    excerpt: "September's Canva update also turns hand-drawn shapes into image frames and adds analytics and payment links to Canva websites.",
    disciplines: ["brand", "web", "graphic"],
    date: "2026-09-27",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Canva Design School", url: "https://www.canva.com/design-school/resources/whats-new-canva-sep26/" }],
    body: [
      "Canva's September release is a grab-bag, but a few of the changes will save real time for designers working with small clients.",
      "## Brand kits from a URL",
      "Paste a website address and Canva will generate a brand kit from it. For freelancers onboarding a client who has a site but no brand guidelines, that's a useful head start. Treat the result as a draft: automated extraction can pick up stray colours or the wrong fonts, so check it before you share it with the client.",
      "## Frames from your own doodles",
      "You can now draw a shape by hand and turn it into an image frame. It's a small thing, but it opens up more expressive photo layouts without opening another app.",
      "## Websites, sheets and whiteboards",
      "- Canva websites get custom navigation, buttons and Google Analytics tracking.",
      "- A PayPal app lets you embed payment links directly in designs.",
      "- Sheets adds tags, filters and conditional formatting.",
      "- Whiteboards gain sections and direct linking.",
      "- A Code feature can generate visual dashboards from spreadsheets and web research.",
      "## Our take",
      "Canva keeps moving from making graphics to running whole small-business workflows. If your clients already live in Canva, these updates make it easier to hand over files they can keep up to date themselves.",
    ],
  },
  {
    type: "news",
    slug: "midjourney-v8-2-edit-model",
    title: "Midjourney's V8.2 edit model lets you change images with plain instructions",
    excerpt: "Inpainting, outpainting and up to four reference images arrived over the last month, along with live style previews.",
    disciplines: ["graphic", "brand", "3d"],
    date: "2026-09-25",
    readMins: 3,
    author: "barry",
    sources: [
      { name: "Midjourney updates", url: "https://updates.midjourney.com/" },
      { name: "Releasebot", url: "https://releasebot.io/updates/midjourney" },
    ],
    body: [
      "Midjourney spent September making its V8 generation of models much easier to steer after the first image comes out.",
      "## Edit with a sentence",
      "The V8.2 edit model, which first appeared on 27 August, lets you change an image by describing the change. It handles inpainting and outpainting, and you can attach up to four reference images to guide the edit. Since 2 September it has been available directly in the lightbox, so you no longer need a separate editing step.",
      "## Style previews and seamless tiles",
      "- The Styles sidebar can now show what your latest prompt would look like across different styles before you commit.",
      "- You can save default parameters so every new prompt starts the way you like.",
      "- Tile generation for V8.1 and V8.2 now blends seams better, which matters for patterns and textures.",
      "## What it means for your workflow",
      "Instruction-based editing is where AI image tools become practical for client work. Instead of re-rolling until a hand looks right, you fix the hand. Reference images help keep a product or character consistent across a set. You'll still need to finish the work in your own tools, but the gap between a first draft and something usable is getting smaller.",
      "As always with generated imagery, check the terms of your plan and your client's policy on AI-made assets before anything ships.",
    ],
  },
  {
    type: "news",
    slug: "mclaren-new-logo-garage-sign",
    title: "McLaren's new logo comes from a garage sign in Auckland",
    excerpt: "An all-caps wordmark, a custom typeface and a palette pulled from an old photo of Bruce McLaren. Heritage done with restraint.",
    disciplines: ["brand", "graphic"],
    date: "2026-09-23",
    readMins: 3,
    author: "barry",
    sources: [{ name: "Carscoops", url: "https://www.carscoops.com/2026/09/mclaren-new-logo/" }],
    body: [
      "McLaren Automotive revealed a new identity on 22 September, and the story behind it is a good one. The wordmark takes its cue from the sign of a service station in Auckland, New Zealand, owned by Bruce McLaren's parents. It was in that garage that the young McLaren modified the 1929 Austin Seven that gave him his first racing win.",
      "## What's new",
      "- A custom typeface, McLaren Sans.",
      "- An all-uppercase wordmark, replacing the previous mixed-case logo.",
      "- A distinctive horizontal line beneath the C.",
      "- A refined palette taken from a photograph of Bruce McLaren: Papaya orange, Ember, Midnight blue, Black, Anthracite, Colnbrook silver and Mist white.",
      "The work was led by David Woodhouse, McLaren Automotive's chief creative officer. The identity will appear on cars, starting with the McL 6GT, and across merchandise and digital channels as it rolls out.",
      "## Why it works",
      "Heritage rebrands often go wrong by copying the past too literally. This one borrows a single, specific detail from the brand's origin story and builds a modern system around it. The colour names do quiet storytelling too. It's a useful example to keep for your next pitch to a client with a long history.",
    ],
  },
  {
    type: "news",
    slug: "affinity-3-3-canva-prosuite",
    title: "Affinity 3.3 lands with a Blend tool, InDesign import and a new ProSuite",
    excerpt: "Canva's free all-in-one design app gets more than 60 features, and now sits in a professional bundle with Cavalry, Flourish and Leonardo.",
    disciplines: ["graphic", "brand", "motion"],
    date: "2026-09-16",
    featured: true,
    readMins: 4,
    author: "barry",
    sources: [
      { name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" },
      { name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" },
    ],
    body: [
      "Canva released Affinity 3.3 on 15 September. Affinity is the app that combines photo editing, vector design and page layout in one place, and it's still free to use with a Canva account on Windows and macOS.",
      "## The headline features",
      "- A Blend tool that morphs one shape into another along a curve, something illustrators have wanted for years.",
      "- A Mask tool, a Deform tool and new saturation and hue curves for image editing.",
      "- Import of InDesign INDD files, which makes switching away from Adobe for layout work far more realistic.",
      "- A JavaScript-based Scripting Studio for automating repetitive jobs.",
      "- Photography upgrades including RAW presets, better sharpening and a dedicated astrophotography workspace.",
      "## Meet ProSuite",
      "Canva also introduced ProSuite, its name for a family of professional tools: Affinity for design, Cavalry for motion graphics, Flourish for data visualisation and Leonardo for generative AI. For now they remain separate apps, with closer integration planned. Affinity and Cavalry stay free; the AI features need a paid Canva plan.",
      "## Should you switch?",
      "If you've been waiting for INDD import before trying Affinity for layout, now is the time to test it on a real project. Open an old InDesign file, check fonts and styles carefully, and see how much survives. For many freelancers, a capable free tool is now a genuine alternative to a subscription.",
    ],
  },
  {
    type: "news",
    slug: "figma-nested-folders-ai-credit-limits",
    image: { src: "/art/figma-nested-folders-ai-credit-limits.webp", alt: "Illustration of colourful folders nested inside each other, many layers deep" },
    title: "Figma projects become nested folders, ten levels deep",
    excerpt: "Teams can finally organise files the way they think, and admins get per-person limits on AI credits.",
    disciplines: ["ui-ux", "web"],
    date: "2026-08-05",
    readMins: 2,
    author: "barry",
    sources: [{ name: "Figma release notes", url: "https://www.figma.com/release-notes/" }],
    body: [
      "Two quality-of-life changes landed in Figma in early August, and both matter more for big teams than the flashier launches do.",
      "## Projects are now folders",
      "Every team file now lives in a folder, and folders can nest up to ten levels deep. You can colour-code them, and nested folders inherit access permissions from their parent, with the option to restrict a folder to specific people. If your team has been faking hierarchy with naming conventions like ‘2026 / Client / Web / v3’, you can finally stop.",
      "## Limits on AI credits",
      "Admins can now set a custom AI credit limit for individual people. When someone hits their limit, they can request more from an admin rather than being stuck. It's a sensible control as AI features use up more of each plan's credits.",
      "## Quick tip",
      "Before restructuring, agree a folder template with your team, for example Client → Project → Phase, so everyone files work the same way from day one.",
    ],
  },
];
