import type { Item } from "./content";

/**
 * October 2026 refresh for Tips, Software, AI models and Videos.
 * Each entry ties back to something that just happened and links its sources.
 */
export const UPDATES: Item[] = [
  // ───────────────────────── Week of 5 October
  {
    type: "tip",
    slug: "phone-edit-client-preview",
    title: "Cut a 4K client preview on your phone",
    excerpt: "Premiere's free mobile app exports 4K with no watermark. Here's a fast routine for sending a rough cut from anywhere.",
    disciplines: ["motion"],
    date: "2026-10-05",
    meta: { tool: "Premiere (mobile)" },
    sources: [{ name: "Creative Bloq", url: "https://www.creativebloq.com/photography/video-editing-software/free-premiere-on-android-is-exactly-the-direction-adobe-should-be-taking" }],
    body: [
      "1. Shoot or drop your clips into one album first, so the import screen isn't a scroll through your whole camera roll.",
      "2. Lay the story out on the main track before touching transitions. Get the order right, then the timing.",
      "3. Record the voice-over in the app and run Enhance Audio on it straight away.",
      "4. Add a simple text card with the version number and date, so the client can't confuse cuts.",
      "5. Export in 4K, but send a 1080p copy for review. It uploads faster and nobody judges a rough cut at full resolution.",
    ],
  },
  {
    type: "tip",
    slug: "draw-the-real-mountain",
    title: "Draw the real mountain, not a triangle",
    excerpt: "Landscape logos work best when they point at somewhere real. A four-step way to keep the specific shape while simplifying.",
    disciplines: ["brand", "graphic"],
    date: "2026-10-04",
    meta: { tool: "Any" },
    sources: [{ name: "Creative Bloq", url: "https://www.creativebloq.com/design/logos-icons/everyones-making-mountain-inspired-logos-in-2026-heres-what-that-tells-us" }],
    body: [
      "1. Find a photo of the actual place from the angle locals know best.",
      "2. Trace only the skyline: one continuous line, no shading.",
      "3. Simplify in passes, removing one bump at a time. Stop just before it stops looking like that mountain.",
      "4. Check it at 24 px. If the silhouette still reads, you've kept the part that makes it specific.",
      "Show the client the photo next to the mark. That's the story they'll repeat to everyone else.",
    ],
  },
  {
    type: "tip",
    slug: "check-ai-mattes",
    title: "Check an AI matte like a compositor would",
    excerpt: "Tools like LTX-2.5 can pull mattes around hair and smoke. Here's how to catch the frames where they slip.",
    disciplines: ["motion", "3d"],
    date: "2026-10-04",
    meta: { tool: "Any compositor" },
    sources: [{ name: "LTX", url: "https://ltx.io/solution/vfx" }],
    body: [
      "1. View the alpha on its own as black and white. Mistakes hide when you look at the colour comp.",
      "2. Put the cut-out over a bright red and then a bright green background to expose edge fringing.",
      "3. Scrub the fastest-moving section frame by frame. Matte errors cluster around motion blur.",
      "4. Fix the bad frames by hand rather than regenerating everything. Small manual paint-outs are quicker than another full pass.",
    ],
  },
  {
    type: "software",
    slug: "premiere-mobile",
    title: "Premiere (mobile)",
    excerpt: "Adobe's free phone editor, now on Android as well as iPhone, with a multi-track timeline and unlimited 4K exports.",
    disciplines: ["motion"],
    date: "2026-10-05",
    meta: { maker: "Adobe", platforms: "iOS, Android 13+", pricing: "Free; Firefly tools use generative credits" },
    sources: [{ name: "Creative Bloq", url: "https://www.creativebloq.com/photography/video-editing-software/free-premiere-on-android-is-exactly-the-direction-adobe-should-be-taking" }],
    body: [
      "A cut-down Premiere for phones. You don't need a Creative Cloud plan or an Adobe account for the core editor, and exports have no watermark.",
      "## Highlights",
      "- Multi-track, frame-accurate timeline.",
      "- Voice-over recording and Enhance Audio noise cleanup.",
      "- Creator templates and unlimited 4K exports.",
      "## Coming soon",
      "- Keyframes, beat detection, Adobe Fonts and opening projects on desktop.",
      "## Best for",
      "- Social cuts and quick client previews away from your desk.",
    ],
  },
  {
    type: "software",
    slug: "caddis",
    title: "Caddis",
    excerpt: "New motion graphics app that mixes node-based and layer-based animation. Version 1.1 adds particles, loops and grids.",
    disciplines: ["motion"],
    date: "2026-10-04",
    meta: { maker: "Mike Gaynor", url: "https://www.caddis.app/", linkLabel: "Visit caddis.app" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/10/new-3d-software-you-may-have-missed-4-october-2026/" }],
    body: [
      "Caddis lets you build motion with nodes, layers or both. It suits procedural work: patterns, grids and systems that react to rules.",
      "## New in 1.1",
      "- Particles with collisions and flocking.",
      "- Loop, For Each and Switch controls.",
      "- Layout and Cell nodes for grids.",
      "- Cryptomatte EXR support and nested compositions.",
      "## Best for",
      "- Motion designers who like Cavalry-style procedural thinking.",
    ],
  },
  {
    type: "software",
    slug: "pftrack-solo",
    title: "PFTrack Solo",
    excerpt: "Professional camera tracking for one-person studios, now with photogrammetry, stereo solving and optical flow included.",
    disciplines: ["3d", "motion"],
    date: "2026-10-04",
    meta: { maker: "The Pixel Farm", platforms: "Windows, macOS, Rocky Linux", pricing: "£999 perpetual, or rent-to-own" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/10/the-pixel-farm-lifts-feature-restrictions-on-pftrack-solo/" }],
    body: [
      "PFTrack matches real camera moves so you can put 3D elements into live-action footage. From version 26.09.30 the Solo edition includes 37 nodes that used to be reserved for bigger studios.",
      "## Now included",
      "- Photogrammetry, Z-depth and Optical Flow.",
      "- Stereo, spherical and equirectangular tracking.",
      "- The Mocap Solver and retiming tools.",
      "## Still Studio-only",
      "- Python API, command-line processing and RED/ARRI RAW debayering.",
    ],
  },
  {
    type: "ai-model",
    slug: "ltx-2-5",
    title: "LTX-2.5",
    excerpt: "Lightricks' open-weights video model, now with VFX tools for alpha mattes, HDR output and turning 3D blockouts into finished shots.",
    disciplines: ["motion", "3d"],
    date: "2026-10-04",
    featured: true,
    meta: { maker: "Lightricks", modality: "Video", pricing: "Open weights free; LTX Studio uses credits", url: "https://ltx.io/model/ltx-2-5", linkLabel: "Visit ltx.io" },
    sources: [
      { name: "CG Channel", url: "https://www.cgchannel.com/2026/10/new-3d-software-you-may-have-missed-4-october-2026/" },
      { name: "LTX", url: "https://ltx.io/solution/vfx" },
    ],
    body: [
      "LTX-2.5 is a video generation model you can run yourself. The weights are on Hugging Face, it works in ComfyUI and Lightricks says it runs on a 12 GB graphics card.",
      "## VFX features",
      "- Alpha Gen: soft-edged mattes for hair, fur, smoke, fire, glass and water.",
      "- Layout to Render: rough 3D blocking in, rendered-looking shot out.",
      "- SDR to HDR and 16-bit EXR output.",
      "- Refine, Restore and Native Resolution for upscaling and cleanup.",
      "- Camera-control LoRAs for directed moves.",
      "## Good for",
      "- Pre-visualisation and rotoscoping help.",
      "- Studios that need to keep client footage on their own machines.",
    ],
  },
  {
    type: "video",
    slug: "caddis-1-1-overview",
    title: "Caddis 1.1: particles, layouts, loops and more",
    excerpt: "The official tour of what's new in the node-and-layer motion graphics app.",
    disciplines: ["motion"],
    date: "2026-10-04",
    featured: true,
    meta: { maker: "Caddis", handle: "Caddis", youtubeId: "WQBUncz23Zs", url: "https://www.youtube.com/watch?v=WQBUncz23Zs", linkLabel: "Watch on YouTube" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/10/new-3d-software-you-may-have-missed-4-october-2026/" }],
    body: [
      "A quick way to see whether Caddis fits how you work. Watch the particle and loop sections in particular: they show how far you can get with rules instead of keyframes.",
    ],
  },
  {
    type: "video",
    slug: "rodeo-fx-fm-insurance-breakdown",
    title: "Rodeo FX: liquid metal and giant waves for FM",
    excerpt: "A VFX breakdown of a fully CG liquid-metal ribbon and ocean waves crashing into a 3D seafront.",
    disciplines: ["3d", "motion"],
    date: "2026-10-02",
    meta: { maker: "Rodeo FX", handle: "Rodeo FX", youtubeId: "Z_vZs7r44Fo", url: "https://www.youtube.com/watch?v=Z_vZs7r44Fo", linkLabel: "Watch on YouTube" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/10/see-rodeo-fxs-vfx-breakdown-of-its-new-ad-for-fm-insurance/" }],
    body: [
      "Directed by Antoine Bardou-Jacquet for insurer FM, the ad follows a ribbon of liquid metal through every shot. The breakdown shows how the ribbon and the ocean simulations were built layer by layer, which is useful study for anyone doing simulation-heavy motion work.",
    ],
  },

  // ───────────────────────── Tips tied to this month's news
  {
    type: "tip",
    slug: "test-your-logo-as-light",
    title: "Test your logo as a glowing badge",
    excerpt: "Car brands are simplifying marks so they read when backlit. Run the same test on yours in two minutes.",
    disciplines: ["brand", "graphic"],
    date: "2026-10-01",
    meta: { tool: "Any" },
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/09/30/vauxhall-griffin-logo-streamline/" }],
    body: [
      "Vauxhall just removed the flag from its griffin partly because fine detail turns to mush when a logo is lit up. Screens, app icons and signage do the same thing to your marks.",
      "1. Place the logo in white on a near-black background.",
      "2. Add a soft outer glow and a small blur, around 2–4 px at 64 px wide.",
      "3. Shrink it to 32 px and step back from the screen.",
      "4. If any shape merges with its neighbour, thicken it, open the gap or drop the detail.",
      "Keep this glowing version in your brand files. It's a useful stress test for every future revision.",
    ],
  },
  {
    type: "tip",
    slug: "figma-folder-template",
    title: "Set a folder template before you nest Figma files",
    excerpt: "Figma folders now nest ten levels deep. Agree one structure first, or you'll just have deeper chaos.",
    disciplines: ["ui-ux", "web"],
    date: "2026-09-30",
    meta: { tool: "Figma" },
    sources: [{ name: "Figma release notes", url: "https://www.figma.com/release-notes/" }],
    body: [
      "1. Pick three levels everyone understands, for example Client → Project → Phase.",
      "2. Give each level a colour: one for active work, one for archived, one for shared resources.",
      "3. Set access on the top folder only. Nested folders inherit permissions, so restrict deeper folders only when you really need to.",
      "4. Pin the template structure in your team's onboarding doc so new people file work the same way.",
    ],
  },
  {
    type: "tip",
    slug: "edit-ai-images-dont-reroll",
    title: "Fix AI images with an edit, not another re-roll",
    excerpt: "Instruction-based editing is now built into tools like Midjourney V8.2. Change one thing at a time and keep what works.",
    disciplines: ["graphic", "brand"],
    date: "2026-09-26",
    meta: { tool: "Midjourney" },
    sources: [{ name: "Midjourney updates", url: "https://updates.midjourney.com/" }],
    body: [
      "1. Pick the image that is closest to right, even if one part is wrong.",
      "2. Write the edit as one plain instruction: ‘make the mug matte black’, not a whole new prompt.",
      "3. Attach a reference image when consistency matters, such as a product or a character. Midjourney's edit model accepts up to four.",
      "4. Make one change per pass. Stacking edits in one instruction makes it hard to tell what helped.",
      "Save each good step so you can go back if a later edit drifts.",
    ],
  },
  {
    type: "tip",
    slug: "check-a-brand-kit-from-url",
    title: "Clean up an auto-generated brand kit before you share it",
    excerpt: "Canva can now build a brand kit from a website address. Five checks turn that draft into something you can trust.",
    disciplines: ["brand", "web"],
    date: "2026-09-28",
    meta: { tool: "Canva" },
    sources: [{ name: "Canva Design School", url: "https://www.canva.com/design-school/resources/whats-new-canva-sep26/" }],
    body: [
      "1. Delete colours that only appear in photos or ads on the site. Keep the ones used in the interface.",
      "2. Check the fonts against the client's licence. A web font on their site isn't always licensed for print.",
      "3. Replace any low-resolution logo with the original vector file.",
      "4. Name each colour by role, such as Primary, Accent or Text, not just by hex value.",
      "5. Ask the client to confirm the kit before you use it in a single design.",
    ],
  },
  {
    type: "tip",
    slug: "move-indesign-files-to-affinity",
    title: "Moving an InDesign file to Affinity: a five-step check",
    excerpt: "Affinity 3.3 can open INDD files. Test with this checklist before you trust it with a real print job.",
    disciplines: ["graphic", "brand"],
    date: "2026-09-17",
    meta: { tool: "Affinity" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" }],
    body: [
      "1. Install every font the document uses before opening it, so nothing gets substituted silently.",
      "2. Open a copy of the INDD file, never your only original.",
      "3. Compare page by page against a PDF exported from InDesign: text flow, hyphenation, kerning and image crops.",
      "4. Check paragraph and character styles survived with the right names, so later edits stay consistent.",
      "5. Export a test PDF with your printer's preset and preflight it before you send anything to press.",
    ],
  },

  // ───────────────────────── Software
  {
    type: "software",
    slug: "affinity",
    title: "Affinity",
    excerpt: "One free app for photo editing, vector design and page layout. Version 3.3 adds a Blend tool, InDesign import and scripting.",
    disciplines: ["graphic", "brand"],
    date: "2026-09-16",
    featured: true,
    meta: { maker: "Canva", platforms: "Windows, macOS", pricing: "Free; AI features need a paid Canva plan", url: "https://www.affinity.studio/", linkLabel: "Get Affinity" },
    sources: [
      { name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" },
      { name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" },
    ],
    body: [
      "Affinity combines what used to be three separate apps (photo editing, vector illustration and page layout) in one free download from Canva.",
      "## New in 3.3",
      "- Blend tool for morphing shapes along a curve.",
      "- InDesign INDD import for moving layout work across.",
      "- Mask and Deform tools, plus hue and saturation curves.",
      "- Scripting Studio for automating repetitive tasks with JavaScript.",
      "- An astrophotography workspace and RAW development presets.",
      "## Best for",
      "- Freelancers who want professional tools without a subscription.",
      "- Designers who jump between photo, vector and layout in one project.",
    ],
  },
  {
    type: "software",
    slug: "cavalry",
    title: "Cavalry",
    excerpt: "Procedural 2D motion design app, now part of Canva's ProSuite and free to use.",
    disciplines: ["motion"],
    date: "2026-09-16",
    meta: { maker: "Canva", platforms: "Windows, macOS", pricing: "Free", url: "https://cavalry.studio/", linkLabel: "Visit Cavalry" },
    sources: [{ name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" }],
    body: [
      "Cavalry builds animation from rules and data rather than only keyframes, which makes it strong for generative patterns, data-driven graphics and motion systems.",
      "With the ProSuite launch it picked up around 50 new features. Canva has also announced a way for teams to edit text or colour inside an animation while the core scene stays locked, which would make templated motion much easier to hand over.",
      "## Best for",
      "- Motion designers who think in systems and repeats.",
      "- Animated data graphics and social templates.",
    ],
  },
  {
    type: "software",
    slug: "smol",
    title: "Smol",
    excerpt: "Mac app that compresses and converts images, PDFs, video and audio on your machine, with nothing uploaded.",
    disciplines: ["web", "graphic"],
    date: "2026-10-02",
    meta: { maker: "Smol", platforms: "macOS", pricing: "$29 one-time", url: "https://smolmac.com/", linkLabel: "Visit smolmac.com" },
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Smol shrinks and converts files locally, so client work never touches a third-party server. It batch-processes folders, strips metadata and can upscale images with AI.",
      "## Best for",
      "- Preparing web images and PDFs for email without an online compressor.",
      "- Anyone working under an NDA.",
    ],
  },
  {
    type: "software",
    slug: "avellio",
    title: "Avellio",
    excerpt: "Typography proofing for InDesign that flags overrides, spacing problems, widows and orphans before print.",
    disciplines: ["graphic"],
    date: "2026-10-02",
    meta: { maker: "Avellio", platforms: "InDesign plug-in", pricing: "$40/year or $70 lifetime", url: "https://www.avellio.app/", linkLabel: "Visit avellio.app" },
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Avellio adds a quality-assurance pass to InDesign, catching the small typographic mistakes that are easy to miss on screen and expensive to fix after printing.",
      "## Best for",
      "- Long documents, reports and books.",
      "- Studios that want a consistent proofing step before sign-off.",
    ],
  },
  {
    type: "software",
    slug: "pigment",
    title: "Pigment",
    excerpt: "Free palette generator from ShapeFactory that builds colour schemes from light and pigment, not random hues.",
    disciplines: ["graphic", "brand", "web"],
    date: "2026-10-02",
    meta: { maker: "ShapeFactory", platforms: "Web", pricing: "Free", url: "https://pigment.shapefactory.co/", linkLabel: "Open Pigment" },
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Pigment generates palettes that feel physically related, as if the colours were mixed and lit together. Export to Adobe Swatch Exchange, SVG or Sketch.",
      "## Best for",
      "- Starting a brand or illustration palette quickly.",
    ],
  },

  // ───────────────────────── AI models
  {
    type: "ai-model",
    slug: "leonardo",
    title: "Leonardo",
    excerpt: "Canva-owned image and video generator with its own models, sketch-to-image and custom model training.",
    disciplines: ["graphic", "3d", "brand"],
    date: "2026-09-16",
    meta: { maker: "Leonardo.Ai (Canva)", modality: "Image, video", pricing: "Free tier, paid plans", url: "https://leonardo.ai/", linkLabel: "Visit leonardo.ai" },
    sources: [
      { name: "Wikipedia", url: "https://en.wikipedia.org/wiki/Leonardo.ai" },
      { name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" },
    ],
    body: [
      "Leonardo was founded in Sydney in 2022 and bought by Canva in 2024. It now sits in Canva's ProSuite next to Affinity, Cavalry and Flourish.",
      "## What it does",
      "- Text-to-image with its own models, including Phoenix and Lucid Origin.",
      "- A real-time canvas that turns rough sketches into images as you draw.",
      "- Motion features that animate still images into short video.",
      "- Custom model training on your own images for a consistent style.",
      "## Good for",
      "- Concept art and game assets in a consistent style.",
      "- Designers already working in the Canva ecosystem.",
    ],
  },

  // ───────────────────────── Videos
  {
    type: "video",
    slug: "blender-5-2-lts-official-overview",
    title: "What's new in Blender 5.2 LTS",
    excerpt: "The Blender team's own tour of the first long-term support release in the 5.x series, supported until July 2028.",
    disciplines: ["3d", "motion"],
    date: "2026-09-30",
    featured: true,
    meta: { maker: "Blender", handle: "Blender", youtubeId: "g4OXlrxqIx0", url: "https://www.youtube.com/watch?v=g4OXlrxqIx0", linkLabel: "Watch on YouTube" },
    sources: [{ name: "Blender 5.2 release notes", url: "https://www.blender.org/download/releases/5-2/" }],
    body: [
      "Blender 5.2 LTS landed on 14 July 2026 and will get fixes until July 2028, which makes it the safe version for studios to standardise on.",
      "## Worth watching for",
      "- Audio-reactive geometry with the new Sample Sound Frequencies node.",
      "- Node-based cloth and hair physics using an XPBD solver.",
      "- A procedural Mesh Bevel node and native LoopTools operators.",
      "- EEVEE running up to twice as fast in instance-heavy scenes.",
    ],
  },
  {
    type: "video",
    slug: "figma-release-notes-september-2026",
    title: "Figma release notes: September 2026",
    excerpt: "Figma's monthly round-up of what changed in the editor, straight from the team that built it.",
    disciplines: ["ui-ux", "web"],
    date: "2026-09-29",
    meta: { maker: "Figma", handle: "Figma", youtubeId: "1lnuBH7CbEY", url: "https://www.youtube.com/watch?v=1lnuBH7CbEY", linkLabel: "Watch on YouTube" },
    sources: [{ name: "Figma release notes", url: "https://www.figma.com/release-notes/" }],
    body: [
      "Figma's release-notes videos are the quickest way to catch up on small changes that never make it into a keynote. Watch with the editor open and try each feature as it comes up.",
    ],
  },
  {
    type: "video",
    slug: "figma-config-2026-closing-keynote",
    title: "Config 2026 closing keynote with Dylan Field",
    excerpt: "Figma's CEO on where the product is heading after a Config that introduced Figma Motion, shaders and code layers.",
    disciplines: ["ui-ux", "web", "motion"],
    date: "2026-09-22",
    meta: { maker: "Figma", handle: "Figma", youtubeId: "SQji6izodIE", url: "https://www.youtube.com/watch?v=SQji6izodIE", linkLabel: "Watch on YouTube" },
    sources: [{ name: "Figma Newsroom", url: "https://www.figma.com/newsroom/" }],
    body: [
      "Config 2026 brought Figma Motion, shaders, generative plugins and code layers onto the canvas. The closing keynote is the best single place to understand how Figma sees those pieces fitting together.",
    ],
  },
  {
    type: "video",
    slug: "affinity-3-3-image-editing-live",
    title: "Affinity 3.3: image editing features, live",
    excerpt: "James Ritson walks through 3.3's photo tools, including the new astrophotography workspace.",
    disciplines: ["graphic"],
    date: "2026-09-18",
    meta: { maker: "James Ritson", handle: "James Ritson", youtubeId: "aVuFGqYyIlk", url: "https://www.youtube.com/watch?v=aVuFGqYyIlk", linkLabel: "Watch on YouTube" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" }],
    body: [
      "If you edit photos in Affinity, this long-form live session shows the new masking, curves and sharpening tools in real use rather than in a quick feature reel.",
    ],
  },
];

/** Additions to existing entries so they reflect this month's news. */
export const PATCHES: Record<string, { date?: string; appendBody: string[]; sources: { name: string; url: string }[] }> = {
  blender: {
    date: "2026-09-30",
    appendBody: [
      "## New in 5.2 LTS",
      "Blender 5.2 is a long-term support release, supported until July 2028. Highlights include audio-reactive geometry nodes, node-based cloth and hair physics, a Mesh Bevel node and faster EEVEE in instance-heavy scenes.",
    ],
    sources: [{ name: "Blender 5.2 release notes", url: "https://www.blender.org/download/releases/5-2/" }],
  },
  midjourney: {
    date: "2026-09-25",
    appendBody: [
      "## New this month",
      "The V8.2 edit model lets you change an image with a plain instruction, including inpainting and outpainting, with up to four reference images. The Styles sidebar can now preview your prompt across styles before you generate.",
    ],
    sources: [{ name: "Midjourney updates", url: "https://updates.midjourney.com/" }],
  },
  "adobe-firefly": {
    date: "2026-10-04",
    appendBody: [
      "## Hints of 3D",
      "A newly published Adobe patent filing describes generating walkable 3D worlds from a text prompt, by first making a 360-degree image and then building geometry from it. It's a filing, not a product, but it points at where Firefly could go next.",
      "## Adobe's creative agent",
      "Since June, an AI agent in public beta can carry out multi-step jobs across Photoshop, Illustrator, InDesign, Premiere and Frame.io, such as swapping backgrounds, reorganising layers or updating a layout with new branding. After Effects is in private beta.",
    ],
    sources: [
      { name: "Adobe", url: "https://news.adobe.com/news/2026/06/adobe-unveils-major-expansion" },
      { name: "Creative Bloq", url: "https://www.creativebloq.com/design/graphic-design/adobes-ai-text-to-3d-world-concept-is-a-glimpse-of-where-firefly-could-go-next" },
    ],
  },
};
