import type { Item } from "./content";

/**
 * October 2026 refresh for Tips, Software, AI models and Videos.
 * Each entry ties back to something that just happened and links its sources.
 */
export const UPDATES: Item[] = [
  // ───────────────────────── Tips tied to this month's news
  {
    type: "tip",
    slug: "test-your-logo-as-light",
    title: "Test your logo as a glowing badge",
    excerpt: "Car brands are simplifying marks so they read when backlit. Run the same test on yours in two minutes.",
    disciplines: ["brand", "graphic"],
    date: "2026-10-01",
    meta: { tool: "Any" },
    sources: [{ name: "Dezeen", url: "https://www.dezeen.com/2026/09/30/vauxhall-griffin-logo-streamline/" }],
    body: [
      "Vauxhall just removed the flag from its griffin partly because fine detail turns to mush when a logo is lit up. Screens, app icons and signage do the same thing to your marks.",
      "1. Place the logo in white on a near-black background.",
      "2. Add a soft outer glow and a small blur, around 2–4 px at 64 px wide.",
      "3. Shrink it to 32 px and step back from the screen.",
      "4. If any shape merges with its neighbour, thicken it, open the gap or drop the detail.",
      "Keep this glowing version in your brand files. It's a useful stress test for every future revision.",
    ],
  },
  {
    type: "tip",
    slug: "figma-folder-template",
    title: "Set a folder template before you nest Figma files",
    excerpt: "Figma folders now nest ten levels deep. Agree one structure first, or you'll just have deeper chaos.",
    disciplines: ["ui-ux", "web"],
    date: "2026-09-30",
    meta: { tool: "Figma" },
    sources: [{ name: "Figma release notes", url: "https://www.figma.com/release-notes/" }],
    body: [
      "1. Pick three levels everyone understands, for example Client → Project → Phase.",
      "2. Give each level a colour: one for active work, one for archived, one for shared resources.",
      "3. Set access on the top folder only. Nested folders inherit permissions, so restrict deeper folders only when you really need to.",
      "4. Pin the template structure in your team's onboarding doc so new people file work the same way.",
    ],
  },
  {
    type: "tip",
    slug: "edit-ai-images-dont-reroll",
    title: "Fix AI images with an edit, not another re-roll",
    excerpt: "Instruction-based editing is now built into tools like Midjourney V8.2. Change one thing at a time and keep what works.",
    disciplines: ["graphic", "brand"],
    date: "2026-09-26",
    meta: { tool: "Midjourney" },
    sources: [{ name: "Midjourney updates", url: "https://updates.midjourney.com/" }],
    body: [
      "1. Pick the image that is closest to right, even if one part is wrong.",
      "2. Write the edit as one plain instruction: ‘make the mug matte black’, not a whole new prompt.",
      "3. Attach a reference image when consistency matters, such as a product or a character. Midjourney's edit model accepts up to four.",
      "4. Make one change per pass. Stacking edits in one instruction makes it hard to tell what helped.",
      "Save each good step so you can go back if a later edit drifts.",
    ],
  },
  {
    type: "tip",
    slug: "check-a-brand-kit-from-url",
    title: "Clean up an auto-generated brand kit before you share it",
    excerpt: "Canva can now build a brand kit from a website address. Five checks turn that draft into something you can trust.",
    disciplines: ["brand", "web"],
    date: "2026-09-28",
    meta: { tool: "Canva" },
    sources: [{ name: "Canva Design School", url: "https://www.canva.com/design-school/resources/whats-new-canva-sep26/" }],
    body: [
      "1. Delete colours that only appear in photos or ads on the site. Keep the ones used in the interface.",
      "2. Check the fonts against the client's licence. A web font on their site isn't always licensed for print.",
      "3. Replace any low-resolution logo with the original vector file.",
      "4. Name each colour by role, such as Primary, Accent or Text, not just by hex value.",
      "5. Ask the client to confirm the kit before you use it in a single design.",
    ],
  },
  {
    type: "tip",
    slug: "move-indesign-files-to-affinity",
    title: "Moving an InDesign file to Affinity: a five-step check",
    excerpt: "Affinity 3.3 can open INDD files. Test with this checklist before you trust it with a real print job.",
    disciplines: ["graphic", "brand"],
    date: "2026-09-17",
    meta: { tool: "Affinity" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" }],
    body: [
      "1. Install every font the document uses before opening it, so nothing gets substituted silently.",
      "2. Open a copy of the INDD file, never your only original.",
      "3. Compare page by page against a PDF exported from InDesign: text flow, hyphenation, kerning and image crops.",
      "4. Check paragraph and character styles survived with the right names, so later edits stay consistent.",
      "5. Export a test PDF with your printer's preset and preflight it before you send anything to press.",
    ],
  },

  // ───────────────────────── Software
  {
    type: "software",
    slug: "affinity",
    title: "Affinity",
    excerpt: "One free app for photo editing, vector design and page layout. Version 3.3 adds a Blend tool, InDesign import and scripting.",
    disciplines: ["graphic", "brand"],
    date: "2026-09-16",
    featured: true,
    meta: { maker: "Canva", platforms: "Windows, macOS", pricing: "Free; AI features need a paid Canva plan", url: "https://www.affinity.studio/", linkLabel: "Get Affinity" },
    sources: [
      { name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" },
      { name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" },
    ],
    body: [
      "Affinity combines what used to be three separate apps (photo editing, vector illustration and page layout) in one free download from Canva.",
      "## New in 3.3",
      "- Blend tool for morphing shapes along a curve.",
      "- InDesign INDD import for moving layout work across.",
      "- Mask and Deform tools, plus hue and saturation curves.",
      "- Scripting Studio for automating repetitive tasks with JavaScript.",
      "- An astrophotography workspace and RAW development presets.",
      "## Best for",
      "- Freelancers who want professional tools without a subscription.",
      "- Designers who jump between photo, vector and layout in one project.",
    ],
  },
  {
    type: "software",
    slug: "cavalry",
    title: "Cavalry",
    excerpt: "Procedural 2D motion design app, now part of Canva's ProSuite and free to use.",
    disciplines: ["motion"],
    date: "2026-09-16",
    meta: { maker: "Canva", platforms: "Windows, macOS", pricing: "Free", url: "https://cavalry.studio/", linkLabel: "Visit Cavalry" },
    sources: [{ name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" }],
    body: [
      "Cavalry builds animation from rules and data rather than only keyframes, which makes it strong for generative patterns, data-driven graphics and motion systems.",
      "With the ProSuite launch it picked up around 50 new features. Canva has also announced a way for teams to edit text or colour inside an animation while the core scene stays locked, which would make templated motion much easier to hand over.",
      "## Best for",
      "- Motion designers who think in systems and repeats.",
      "- Animated data graphics and social templates.",
    ],
  },
  {
    type: "software",
    slug: "smol",
    title: "Smol",
    excerpt: "Mac app that compresses and converts images, PDFs, video and audio on your machine, with nothing uploaded.",
    disciplines: ["web", "graphic"],
    date: "2026-10-02",
    meta: { maker: "Smol", platforms: "macOS", pricing: "$29 one-time", url: "https://smolmac.com/", linkLabel: "Visit smolmac.com" },
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Smol shrinks and converts files locally, so client work never touches a third-party server. It batch-processes folders, strips metadata and can upscale images with AI.",
      "## Best for",
      "- Preparing web images and PDFs for email without an online compressor.",
      "- Anyone working under an NDA.",
    ],
  },
  {
    type: "software",
    slug: "avellio",
    title: "Avellio",
    excerpt: "Typography proofing for InDesign that flags overrides, spacing problems, widows and orphans before print.",
    disciplines: ["graphic"],
    date: "2026-10-02",
    meta: { maker: "Avellio", platforms: "InDesign plug-in", pricing: "$40/year or $70 lifetime", url: "https://www.avellio.app/", linkLabel: "Visit avellio.app" },
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Avellio adds a quality-assurance pass to InDesign, catching the small typographic mistakes that are easy to miss on screen and expensive to fix after printing.",
      "## Best for",
      "- Long documents, reports and books.",
      "- Studios that want a consistent proofing step before sign-off.",
    ],
  },
  {
    type: "software",
    slug: "pigment",
    title: "Pigment",
    excerpt: "Free palette generator from ShapeFactory that builds colour schemes from light and pigment, not random hues.",
    disciplines: ["graphic", "brand", "web"],
    date: "2026-10-02",
    meta: { maker: "ShapeFactory", platforms: "Web", pricing: "Free", url: "https://pigment.shapefactory.co/", linkLabel: "Open Pigment" },
    sources: [{ name: "CreativePro", url: "https://creativepro.com/snippets-october-2026/" }],
    body: [
      "Pigment generates palettes that feel physically related, as if the colours were mixed and lit together. Export to Adobe Swatch Exchange, SVG or Sketch.",
      "## Best for",
      "- Starting a brand or illustration palette quickly.",
    ],
  },

  // ───────────────────────── AI models
  {
    type: "ai-model",
    slug: "leonardo",
    title: "Leonardo",
    excerpt: "Canva-owned image and video generator with its own models, sketch-to-image and custom model training.",
    disciplines: ["graphic", "3d", "brand"],
    date: "2026-09-16",
    meta: { maker: "Leonardo.Ai (Canva)", modality: "Image, video", pricing: "Free tier, paid plans", url: "https://leonardo.ai/", linkLabel: "Visit leonardo.ai" },
    sources: [
      { name: "Wikipedia", url: "https://en.wikipedia.org/wiki/Leonardo.ai" },
      { name: "Creative Boom", url: "https://www.creativeboom.com/news/canva-launches-prosuite-bringing-affinity-cavalry-flourish-and-leonardo-together-with-more-than-new-100-features/" },
    ],
    body: [
      "Leonardo was founded in Sydney in 2022 and bought by Canva in 2024. It now sits in Canva's ProSuite next to Affinity, Cavalry and Flourish.",
      "## What it does",
      "- Text-to-image with its own models, including Phoenix and Lucid Origin.",
      "- A real-time canvas that turns rough sketches into images as you draw.",
      "- Motion features that animate still images into short video.",
      "- Custom model training on your own images for a consistent style.",
      "## Good for",
      "- Concept art and game assets in a consistent style.",
      "- Designers already working in the Canva ecosystem.",
    ],
  },

  // ───────────────────────── Videos
  {
    type: "video",
    slug: "blender-5-2-lts-official-overview",
    title: "What's new in Blender 5.2 LTS",
    excerpt: "The Blender team's own tour of the first long-term support release in the 5.x series, supported until July 2028.",
    disciplines: ["3d", "motion"],
    date: "2026-09-30",
    featured: true,
    meta: { maker: "Blender", handle: "Blender", youtubeId: "g4OXlrxqIx0", url: "https://www.youtube.com/watch?v=g4OXlrxqIx0", linkLabel: "Watch on YouTube" },
    sources: [{ name: "Blender 5.2 release notes", url: "https://www.blender.org/download/releases/5-2/" }],
    body: [
      "Blender 5.2 LTS landed on 14 July 2026 and will get fixes until July 2028, which makes it the safe version for studios to standardise on.",
      "## Worth watching for",
      "- Audio-reactive geometry with the new Sample Sound Frequencies node.",
      "- Node-based cloth and hair physics using an XPBD solver.",
      "- A procedural Mesh Bevel node and native LoopTools operators.",
      "- EEVEE running up to twice as fast in instance-heavy scenes.",
    ],
  },
  {
    type: "video",
    slug: "figma-release-notes-september-2026",
    title: "Figma release notes: September 2026",
    excerpt: "Figma's monthly round-up of what changed in the editor, straight from the team that built it.",
    disciplines: ["ui-ux", "web"],
    date: "2026-09-29",
    meta: { maker: "Figma", handle: "Figma", youtubeId: "1lnuBH7CbEY", url: "https://www.youtube.com/watch?v=1lnuBH7CbEY", linkLabel: "Watch on YouTube" },
    sources: [{ name: "Figma release notes", url: "https://www.figma.com/release-notes/" }],
    body: [
      "Figma's release-notes videos are the quickest way to catch up on small changes that never make it into a keynote. Watch with the editor open and try each feature as it comes up.",
    ],
  },
  {
    type: "video",
    slug: "figma-config-2026-closing-keynote",
    title: "Config 2026 closing keynote with Dylan Field",
    excerpt: "Figma's CEO on where the product is heading after a Config that introduced Figma Motion, shaders and code layers.",
    disciplines: ["ui-ux", "web", "motion"],
    date: "2026-09-22",
    meta: { maker: "Figma", handle: "Figma", youtubeId: "SQji6izodIE", url: "https://www.youtube.com/watch?v=SQji6izodIE", linkLabel: "Watch on YouTube" },
    sources: [{ name: "Figma Newsroom", url: "https://www.figma.com/newsroom/" }],
    body: [
      "Config 2026 brought Figma Motion, shaders, generative plugins and code layers onto the canvas. The closing keynote is the best single place to understand how Figma sees those pieces fitting together.",
    ],
  },
  {
    type: "video",
    slug: "affinity-3-3-image-editing-live",
    title: "Affinity 3.3: image editing features, live",
    excerpt: "James Ritson walks through 3.3's photo tools, including the new astrophotography workspace.",
    disciplines: ["graphic"],
    date: "2026-09-18",
    meta: { maker: "James Ritson", handle: "James Ritson", youtubeId: "aVuFGqYyIlk", url: "https://www.youtube.com/watch?v=aVuFGqYyIlk", linkLabel: "Watch on YouTube" },
    sources: [{ name: "CG Channel", url: "https://www.cgchannel.com/2026/09/canva-releases-affinity-3-3/" }],
    body: [
      "If you edit photos in Affinity, this long-form live session shows the new masking, curves and sharpening tools in real use rather than in a quick feature reel.",
    ],
  },
];

/** Additions to existing entries so they reflect this month's news. */
export const PATCHES: Record<string, { date?: string; appendBody: string[]; sources: { name: string; url: string }[] }> = {
  blender: {
    date: "2026-09-30",
    appendBody: [
      "## New in 5.2 LTS",
      "Blender 5.2 is a long-term support release, supported until July 2028. Highlights include audio-reactive geometry nodes, node-based cloth and hair physics, a Mesh Bevel node and faster EEVEE in instance-heavy scenes.",
    ],
    sources: [{ name: "Blender 5.2 release notes", url: "https://www.blender.org/download/releases/5-2/" }],
  },
  midjourney: {
    date: "2026-09-25",
    appendBody: [
      "## New this month",
      "The V8.2 edit model lets you change an image with a plain instruction, including inpainting and outpainting, with up to four reference images. The Styles sidebar can now preview your prompt across styles before you generate.",
    ],
    sources: [{ name: "Midjourney updates", url: "https://updates.midjourney.com/" }],
  },
  "adobe-firefly": {
    date: "2026-09-20",
    appendBody: [
      "## Adobe's creative agent",
      "Since June, an AI agent in public beta can carry out multi-step jobs across Photoshop, Illustrator, InDesign, Premiere and Frame.io, such as swapping backgrounds, reorganising layers or updating a layout with new branding. After Effects is in private beta.",
    ],
    sources: [{ name: "Adobe", url: "https://news.adobe.com/news/2026/06/adobe-unveils-major-expansion" }],
  },
};
